spring.application.name=canteenflow

# ==================================================
# POSTGRESQL DATABASE
# ==================================================

spring.datasource.url=jdbc:${DATABASE_URL:postgresql://localhost:5432/canteenflow}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==================================================
# HIKARI CONNECTION POOL
# ==================================================

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

# ==================================================
# THYMELEAF
# ==================================================

spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false

# ==================================================
# SERVER
# ==================================================

server.port=${PORT:8080}